[package]
name = "pearl"
version = "0.1.0"
authors = ["Odin <odin.sev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.5.1"
itertools = "0.10.1"
petgraph = "0.6.0"